### ISSUE TITLE
Implement continuous deployment github actions to trigger build of dragonfly-schema-dotnet

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/dragonfly-schema#14]
This is the repo that needs the "CD-style" script like the one on pollination-server. This should trigger a rebuild and re-release of the [dragonfly-schema-dotnet](https://github.com/ladybug-tools/dragonfly-schema-dotnet) repo.

It should send the [Model OpenAPI definition](https://github.com/ladybug-tools/dragonfly-schema/blob/gh-pages/model.json) generated from the [docs stage of travis](https://github.com/ladybug-tools/dragonfly-schema/blob/master/.travis.yml#L31-L43) as the payload.

**Comment by AntoineDao** [comment]
I have added @chriswmackey as I expect we'll be doing a bit of back and forth with the build script implementation.

**Comment by AntoineDao** [comment]
[Done!](https://github.com/ladybug-tools/dragonfly-schema/pull/17)
