### ISSUE TITLE
Automate generating C# SDK from openapi schema

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/dragonfly-schema#6]
Similar to honeybee-schema we will need a dragonfly-schema-dot-net. This will be helpful for Konrad to continue the development for the Revit plugin.

@MingboPeng, let me know when do you think is the right time to do this and I will create a new repository.

**Comment by MingboPeng** [comment]
@mostaphaRoudsari  please do.

**Comment by mostaphaRoudsari** [comment]
Here you go: https://github.com/ladybug-tools/dragonfly-schema-dotnet

**Comment by MingboPeng** [comment]
Thanks!
